### ISSUE TITLE
Error on `examples/get_status.py`

### ISSUE THREAD

**Issue by za** [gopaycommunity/gopay-python-api#19]
Hi there,

I am getting this when executing the `examples/get_status.py`:

```
(gopay-py3.10) ➜  gopay-python-api git:(master) ✗ python3 examples/get_status.py

> /gopay-python-api/gopay/__init__.py(27)payments()
-> config_model = GopayConfig.parse_obj(config)
(Pdb) config
{'goid': 'my goid', 'client_id': 'my id', 'client_secret': 'my secret', 'gateway_url': 'https://gw.sandbox.gopay.com/', 'scope': <TokenScope.ALL: 'payment-all'>, 'language': <Language.CZECH: 'CS'>}
(Pdb) GopayConfig.parse_obj(config)
*** pydantic.error_wrappers.ValidationError: 1 validation error for GopayConfig
goid
  value is not a valid integer (type=type_error.integer)
(Pdb) c
Traceback (most recent call last):
  File "/gopay-python-api/examples/get_status.py", line 4, in <module>
    payments = gopay.payments(
  File "/gopay-python-api/gopay/__init__.py", line 27, in payments
    config_model = GopayConfig.parse_obj(config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GopayConfig
goid
  value is not a valid integer (type=type_error.integer)
```

Am I missing something? Or we should replace `goid` value with an integer?

**Comment by standakouba** [comment]
Hi,
it's exactly as you wrote, you are supposed to replace `goid`, `client_id` and `client_secret`.
Have a look at the tests in `/tests` directory, there are more examples of real usage.

**Comment by za** [comment]
Ah, so is it the example code is written to be broken @standakouba ? https://github.com/gopaycommunity/gopay-python-api/blob/master/examples/get_status.py#L6 CMIIW.

**Comment by za** [comment]
Hi @standakouba any comment/update?
