### ISSUE TITLE
Version 2.2.2 failed on poetry lookup package version

### ISSUE THREAD

**Issue by dark-light-cz** [gopaycommunity/gopay-python-api#38]
If I install latest pypi version 2.2.2 it fails on looking up library version.

There is a mistake in lookup.  As you can see https://github.com/gopaycommunity/gopay-python-api/blob/ff74f70d3886bf0b53ab2a92163bd53c7a2151a1/gopay/utils.py#L6
There is a lookup in root of environment. But in my case I have no projet file.

### How to reproduce?

Just create clean environment, install library with pip, enter environment, run python and import gopay:

```
envname=appenv
python3 -m virtualenv  --python=`which python3` ${envname}

source ${envname}/bin/activate
python3 -m pip install gopay==2.2.2
python3 -c "import gopay"

deactivate
```

### out of such script:

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/appenv/lib/python3.9/site-packages/gopay/__init__.py", line 3, in <module>
    from gopay.api import GoPay
  File "/root/appenv/lib/python3.9/site-packages/gopay/api.py", line 8, in <module>
    from gopay.utils import DEFAULT_USER_AGENT
  File "/root/appenv/lib/python3.9/site-packages/gopay/utils.py", line 11, in <module>
    DEFAULT_USER_AGENT = "GoPay Python " + get_project_version()
  File "/root/appenv/lib/python3.9/site-packages/gopay/utils.py", line 7, in get_project_version
    with open(pyproject_path, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/appenv/lib/python3.9/site-packages/pyproject.toml'

```

### Environment:

OS: Debian 11
Python version: 3.9.2

**Comment by dark-light-cz** [comment]
Was fixed in 2.2.3
